#:schema node_modules/wrangler/config-schema.json
name = "paibp"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-11-01"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "paibp-db"
database_id = "5421b764-4dd8-4bb9-8b4a-015054844882"

[vars]
GEMINI_API_KEY = "AIzaSyD9IObHvnmjZNNKce-ouz1ca660VO3talE"
